#!name=Others
#!desc=Others:去广告、签到

[Rule]
# > YouTube去广告(*.googlevideo.com, *.youtube.com, youtubei.googleapis.com)
URL-REGEX,https?:\/\/.+.googlevideo.com\/ptracking\?pltype=adhost,REJECT
URL-REGEX,https?:\/\/.+.youtube.com\/api\/stats\/ads,REJECT
URL-REGEX,https?:\/\/.+.youtube.com\/get_midroll_,REJECT
URL-REGEX,https?:\/\/.+.youtube.com\/pagead\/,REJECT
URL-REGEX,https?:\/\/.+.youtube.com\/ptracking\?,REJECT
URL-REGEX,https?:\/\/m.youtube.com\/_get_ads,REJECT
URL-REGEX,https?:\/\/premiumyva.appspot.com\/vmclickstoadvertisersite,REJECT
URL-REGEX,https?:\/\/s0.2mdn.net\/ads\/,REJECT
URL-REGEX,https?:\/\/stats.tubemogul.com\/stats\/,REJECT
URL-REGEX,https?:\/\/youtubei.googleapis.com\/.+ad_break,REJECT
URL-REGEX,https?:\/\/youtubei.googleapis.com\/youtubei\/.+(ad|log),REJECT
# > B乎去广告(api.zhihu.com, www.zhihu.com)
USER-AGENT,AVOS*,REJECT-TINYGIF
URL-REGEX,https?://www.zhihu.com/api/v4/mcn/,REJECT
URL-REGEX,https?://api.zhihu.com/(ab|adx|xen|club|fringe|zst|commercial|ad-style-service|market/popover|search/(top|tab|preset)|.*(guide|recommendations|extended|featured-comment-ad)),REJECT
AND,((USER-AGENT,osee2*), (NOT,((DOMAIN-SUFFIX,zhihu.com))), (NOT,((DOMAIN-SUFFIX,zhimg.com)))),REJECT-TINYGIF
# > B站去广告(www.bilibili.com, api.bilibili.com, app.bilibili.com, api.live.bilibili.com)
URL-REGEX,https://app.bilibili.com/x/v2/(splash|search/(defaultword|square)),REJECT
URL-REGEX,https://api.bilibili.com/x/v2/dm/ad,REJECT

[URL Rewrite]
# > tiktok解锁(*.tiktokv.com, *.byteoversea.com, *.musical.ly, *.snssdk.com)
(?<=_region=)CN(?=&) JP 307
(?<=&app_version=)15..(?=.?.?&) 1 307
(?<=\?version_code=)15..(?=.?.?&) 1 307
# > tiktok去水印(*.amemv.com, *.snssdk.com)
^https://aweme-eagle(.*)\.snssdk\.com/aweme/v2/ https://aweme-eagle$1.snssdk.com/aweme/v1/ 302

[Script]
# > YouTube去广告(*.googlevideo.com, *.youtube.com, youtubei.googleapis.com)
YouTube = type=http-request,pattern=https://[\s\S]*\.googlevideo\.com/.*&(oad|ctier),script-path=https://Choler.github.io/Surge/Script/YouTube.js
# > JD签到(api.m.jd.com)
JD_DailyBonus = type=http-request,pattern=https:\/\/api\.m\.jd\.com\/client\.action.*functionId=signBean,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
JD_DailyBonus = type=cron,cronexp="3 0 * * *",script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
# > B乎去广告(api.zhihu.com, www.zhihu.com)
zhihu people = type=http-response,requires-body=1,max-size=0,pattern=https://api.zhihu.com/people/,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20zhihu%20people.js
zhihu feed = type=http-response,requires-body=1,max-size=0,pattern=https://api.zhihu.com/moments/recommend,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20zhihu%20feed.js
zhihu recommend = type=http-response,requires-body=1,max-size=0,pattern=https://api.zhihu.com/topstory/recommend,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20zhihu%20recommend.js
zhihu answer = type=http-response,requires-body=1,max-size=0,pattern=https://api.zhihu.com/v4/questions,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20zhihu%20answer.js
# > tiktok去水印(*.amemv.com, *.snssdk.com)
Aweme = type=http-request,pattern=https:\/\/.*\.amemv\.com\/aweme\/v.*\/(feed|post),script-path=https://Choler.github.io/Surge/Script/Aweme.js
Aweme = type=http-response,pattern=https:\/\/.*\.amemv\.com\/aweme\/v.*\/(feed|post),requires-body=true,script-path=https://Choler.github.io/Surge/Script/Aweme.js
# > B站去广告(www.bilibili.com, api.bilibili.com, app.bilibili.com, api.live.bilibili.com)
bilibili space = type=http-response,requires-body=1,max-size=0,pattern=https://app.bilibili.com/x/v2/space\?access_key,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20space.js
bilibili tab = type=http-response,requires-body=1,max-size=0,pattern=https://app.bilibili.com/x/resource/show/tab\?access_key,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20tab.js
bilibili feed = type=http-response,requires-body=1,max-size=0,pattern=https://app.bilibili.com/x/v2/feed/index\?access_key,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20feed.js
bilibili account = type=http-response,requires-body=1,max-size=0,pattern=https://app.bilibili.com/x/v2/account/mine\?access_key,debug=1,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20account.js
bilibili view = type=http-response,requires-body=1,max-size=0,pattern=https://app.bilibili.com/x/v2/view\?access_key,debug=1,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20view%20relate.js
bilibili reply = type=http-response,requires-body=1,max-size=0,pattern=https://api.bilibili.com/x/v2/reply/main\?access_key,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20reply.js
bilibili live = type=http-response,requires-body=1,max-size=0,pattern=https://api.live.bilibili.com/xlive/app-room/v1/index/getInfoByRoom\?access_key,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20live.js
# > B站签到(manga.bilibili.com)
Manga = type=http-request,pattern=https:\/\/manga\.bilibili\.com\/.*\.User\/GetWallet,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Bilibili-DailyBonus/Manga.js
Manga = type=cron,cronexp="9 0 * * *",script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Bilibili-DailyBonus/Manga.js
# > 52PoJie解锁(www.52pojie.cn)
Get-Cookie = type=http-request,pattern=https:\/\/www\.52pojie\.cn\/home\.php\?,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/52pojieDailyBonus/Get-Cookie.js
52pojie = type=cron,cronexp="0 8 * * *",script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/52pojieDailyBonus/52pojie.js
# > iQIYI签到(*.iqiyi.com)
iQIYI_GetCookie = type=http-request,pattern=https?:\/\/.*\.iqiyi\.com\/.*authcookie=,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/iQIYI-DailyBonus/iQIYI_GetCookie.js
iQIYI_DailyBonus = type=cron,cronexp="9 0 * * *",script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/iQIYI-DailyBonus/iQIYI_DailyBonus.js
# > Bahamut签到(api.gamer.com.tw)
Bahamut = type=http-request,pattern=https:\/\/api\.gamer\.com\.tw\/mobile_app\/anime\/v3\/token\.php,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Bahamut.js
Bahamut = type=http-response,pattern=https:\/\/api\.gamer\.com\.tw\/mobile_app\/anime\/v3\/token\.php,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Bahamut.js

[MITM]
hostname = %APPEND% *.googlevideo.com, *.youtube.com, youtubei.googleapis.com, api.m.jd.com, api.zhihu.com, www.zhihu.com, *.tiktokv.com, *.byteoversea.com, *.musical.ly, *.snssdk.com*.amemv.com, www.bilibili.com, api.bilibili.com, app.bilibili.com, api.live.bilibili.com, manga.bilibili.com, www.52pojie.cn, *.iqiyi.com, api.gamer.com.tw
